# -*- coding: utf-8 -*-
"""
Canonical tool seed for the 2026 Software & AI Tool Directory.

Built from:
  * Primary source OpenAlternative (69 tools) — merged from openalternative/data_content.py
  * AlternativeTo relationships (e.g. Notion -> Obsidian / AppFlowy / PrivacyNotes)
  * Awesome-Selfhosted / GitHub (open-source, self-hosted) — licenses verified via GitHub API
  * Commercial leaders (from knowledge + Capterra/G2-style categories); pricing marked
    "unknown"/"verify" unless certain, never invented.

Every record carries source provenance. Repo name is used to verify license via GitHub API.
"""
import sys, os, datetime
sys.path.insert(0, os.path.dirname(__file__))

# reuse openalternative content
import importlib.util
_spec = importlib.util.spec_from_file_location("dc", os.path.join("openalternative", "data_content.py"))
dc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(dc)

TODAY = datetime.date.today().isoformat()


PRICING_TERMS = {"free", "freemium", "subscription", "usage-based", "one-time",
                 "enterprise", "unknown", "open source", "paid", "verify"}


def rec(tool_id, name, aliases, company, categories, product_type, use_cases, ownership,
        license, repo, availability, hosting, pricing, tech_reqs, user_profile,
        difficulty, setup_effort, technical_involvement, deployment_effort, maintenance,
        customization, opensource, openweight, cloud, local_, selfhosted, web, desktop,
        mobile, android, ios, api, *tail):
    """Resolve the decision tail robustly.

    tail (after `api`) may be authored in two equivalent forms:
      [free_value, best_for, avoid_when, choose_other, sources_list, (notes)]
      [free_flag, pricing_model, best_for, avoid_when, choose_other, sources_list, (notes)]
    We detect where the sources-list sits and derive the 3 decision strings before it.
    """
    src_idx = max((i for i, x in enumerate(tail) if isinstance(x, (list, tuple))), default=-1)
    if src_idx == -1:
        raise ValueError(f"no sources list for {tool_id}")
    sources = list(tail[src_idx])
    notes = tail[src_idx + 1] if len(tail) > src_idx + 1 else ""
    choose_other = tail[src_idx - 1]
    avoid_when = tail[src_idx - 2]
    best_for = tail[src_idx - 3]
    pre = tail[:src_idx - 3]
    if len(pre) == 1:
        free_value = pre[0]
        _pm = free_value.lower().strip() if isinstance(free_value, str) else "verify"
        _free_bool = _pm in ("free", "freemium", "open source")
    elif len(pre) == 2:
        _flag, _pm_raw = pre
        _pm = _pm_raw.lower().strip() if isinstance(_pm_raw, str) else "verify"
        _free_bool = bool(_flag) or _pm in ("free", "freemium", "open source")
    else:
        _pm, _free_bool = "verify", False
    if _pm not in PRICING_TERMS:
        _pm = "verify"
    return {
        "tool_id": tool_id,
        "name": name,
        "aliases": aliases,
        "company": company,
        "categories": categories,
        "product_type": product_type,
        "use_cases": use_cases,
        "ownership": ownership,
        "license": license,
        "license_url": f"https://github.com/{repo}/blob/main/LICENSE" if (repo and license and license not in ("Unknown", "Proprietary")) else None,
        "repository": f"https://github.com/{repo}" if repo else None,
        "repo": repo,
        "availability": availability,
        "hosting": hosting,
        "pricing": pricing,
        "technical_requirements": tech_reqs,
        "user_profile": user_profile,
        "difficulty": difficulty,
        "setup_effort": setup_effort,
        "technical_involvement": technical_involvement,
        "deployment_effort": deployment_effort,
        "maintenance": maintenance,
        "customization": customization,
        "open_source": opensource,
        "open_weight": openweight,
        "cloud": cloud, "local": local_, "self_hosted": selfhosted,
        "web": web, "desktop": desktop, "mobile": mobile, "android": android, "ios": ios,
        "api": api,
        "free_option": _free_bool,
        "pricing_model": _pm,
        "best_for": best_for,
        "avoid_when": avoid_when,
        "choose_other": choose_other,
        "source_count": len(sources),
        "sources": sources,
        "confidence": "high" if len(sources) >= 2 else "medium",
        "last_verified": TODAY,
        "notes": notes,
    }


def build_seed():
    tools = []
    a = tools.append

    # ============ AI CODING / AGENTS / MODELS ============
    a(rec("claude-code", "Claude Code", ["claude code cli"], "Anthropic",
        ["ai-coding", "ai-agents", "dev"], "AI coding agent",
        ["Terminal-based AI coding agent", "Code generation & editing", "autonomous coding"],
        "proprietary", "Proprietary", None,
        ["web", "desktop", "api"], ["cloud"], "subscription",
        ["terminal", "api key required", "local installation"], ["developer"],
        "Intermediate", "Low", "Developer-oriented", "Guided", "Low", "Moderate",
        False, False, True, True, False, False, False, False, False, True, True,
        "subscription", "Developers who want an agentic coding assistant in their terminal/IDE.",
        "Non-developers; those wanting a visual/no-code builder.",
        "Lovable, Cursor, OpenCode (open source).",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/claude-code"},
         {"name": "Official", "url": "https://claude.com/product/claude-code"}],
        "Proprietary; pricing requires verification.")),

    a(rec("lovable", "Lovable", [], "Lovable", ["ai-coding", "dev-frameworks"], "AI app builder",
        ["Build web apps from prompts (no-code)", "rapid prototyping", "SaaS MVP"],
        "proprietary", "Proprietary", None,
        ["web"], ["cloud"], "freemium", ["account required"], ["entrepreneur", "designer", "beginner"],
        "Beginner", "Instant", "None", "None", "None", "Limited",
        False, False, True, False, False, True, False, False, False, False, True,
        "freemium", "Non-developers/entrepreneurs who want a working web app fast.",
        "Developers needing deep code control or offline/local builds.",
        "Bolt, Bolt.diy, Cursor, OpenAI Codex.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/lovable"}],
        "Pricing and free-tier limits require verification.")),

    a(rec("bolt", "Bolt", [], "StackBlitz", ["ai-coding", "dev-frameworks"], "AI app builder",
        ["Prompt-to-app in browser", "full-stack prototypes", "SaaS MVP"],
        "proprietary", "Proprietary", None,
        ["web"], ["cloud"], "freemium", ["account required"], ["entrepreneur", "beginner", "developer"],
        "Beginner", "Instant", "None", "None", "None", "Moderate",
        False, False, True, False, False, True, False, False, False, False, True,
        "freemium", "Users who want browser-based, prompt-driven app building.",
        "Users wanting offline/local self-hosted control.",
        "Bolt.diy, Lovable, Cursor.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/developer-tools/ai-assisted-coding"}],
        "Pricing requires verification.")),

    a(rec("bolt-diy", "Bolt.diy", ["bolt new"], "StackBlitz (community)", ["ai-coding", "dev-frameworks", "selfhost", "dev"],
        "AI app builder (open source)", ["Self-hosted prompt-to-app", "local experimentation", "SaaS MVP"],
        "open source", "MIT", "stackblitz/bolt.new",
        ["web", "local"], ["local", "self-hosted", "cloud"], "free",
        ["node", "npm install", "api key required", "local installation", "build tools"],
        ["developer", "technical team"], "Intermediate", "Medium", "Developer-oriented", "Manual",
        "Moderate", "Very high",
        True, False, False, True, True, True, False, False, False, False, True,
        "free", "Developers who want an open-source, self-hostable prompt-to-app builder.",
        "Non-developers wanting zero-setup.",
        "Lovable, Bolt, Cursor.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/developer-tools/ai-assisted-coding"},
         {"name": "GitHub", "url": "https://github.com/stackblitz/bolt.new"}],
        "Verify license file and self-hosting instructions.")),

    a(rec("cursor", "Cursor", [], "Anysphere", ["ai-coding", "dev-ide"], "AI code editor",
        ["AI-native code editor", "code generation", "code editing"],
        "proprietary", "Proprietary", None,
        ["desktop"], ["cloud", "local"], "freemium",
        ["local installation", "account required"], ["developer"],
        "Intermediate", "Low", "Developer-oriented", "Guided", "Low", "Moderate",
        False, False, True, False, False, False, True, False, False, False, True,
        True, "freemium", "Developers who want an AI assistant embedded in an IDE.",
        "Non-developers; those needing open source or terminal-only.",
        "OpenCode, Claude Code, VS Code + Copilot.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/cursor"}])),

    a(rec("opencode", "OpenCode", ["opencode-ai"], "OpenCode (community)", ["ai-coding", "dev", "selfhost"],
        "AI coding agent", ["Terminal AI coding agent", "75+ LLM providers", "no code storage"],
        "open source", "MIT", "sst/opencode",
        ["web", "desktop", "local"], ["local", "self-hosted"], "free",
        ["terminal", "npm install", "api key required", "build tools"], ["developer"],
        "Intermediate", "Low", "Developer-oriented", "Manual", "Moderate", "High",
        True, False, False, True, True, False, True, False, False, False, True,
        "free", "Developers who want an open, terminal-based agentic coding tool.",
        "Non-developers.",
        "Claude Code, Cursor.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/developer-tools"},
         {"name": "GitHub", "url": "https://github.com/sst/opencode"}],
        "Repo name to confirm via GitHub API.")),

    a(rec("langflow", "Langflow", [], "DataStax", ["ai-models", "ai-agents", "selfhost"],
        "Visual AI builder", ["Drag-and-drop AI agent/RAG builder", "visual workflow", "MCP servers"],
        "open source", "MIT", "langflow-ai/langflow",
        ["web", "local"], ["local", "self-hosted", "cloud"], "free",
        ["python", "pip install", "local installation", "docker recommended"], ["developer", "technical team"],
        "Intermediate", "Medium", "Moderate", "Manual", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, False, True,
        "free", "Developers/teams building visual AI agents and RAG pipelines.",
        "Absolute beginners wanting zero setup.",
        "Dify, Flowise, n8n.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/ai-machine-learning"},
         {"name": "GitHub", "url": "https://github.com/langflow-ai/langflow"}])),

    a(rec("dify", "Dify", [], "Dify.AI", ["ai-models", "ai-agents", "ai-ml-infra", "selfhost"],
        "LLMOps platform", ["Build agentic workflows", "RAG pipelines", "LLM app ops"],
        "open source", "proprietary-core", "langgenius/dify",
        ["web", "local"], ["local", "self-hosted", "cloud"], "freemium",
        ["docker", "local installation"], ["developer", "technical team"],
        "Intermediate", "Medium", "Moderate", "Guided", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, False, True,
        "freemium", "Teams building multi-step LLM applications and RAG.",
        "Non-technical solo users wanting instant setup.",
        "Langflow, Flowise, n8n.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/ai-machine-learning"},
         {"name": "GitHub", "url": "https://github.com/langgenius/dify"}])),

    a(rec("ollama", "Ollama", [], "Ollama", ["ai-models", "ai-ml-infra", "selfhost"],
        "Local LLM runner", ["Run open-source LLMs locally", "local inference", "model serving"],
        "open source", "MIT", "ollama/ollama",
        ["desktop", "local", "api"], ["local", "self-hosted"], "free",
        ["local installation", "terminal", "gpu recommended"], ["developer", "technical team", "researcher"],
        "Intermediate", "Low", "Minimal", "Guided", "Low", "Moderate",
        True, False, False, True, True, False, True, False, False, False, True,
        "free", "Users who want to run open LLMs locally with minimal fuss.",
        "Users needing a hosted managed model API.",
        "LM Studio, vLLM, llama.cpp.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/ai-machine-learning"},
         {"name": "GitHub", "url": "https://github.com/ollama/ollama"}])),

    a(rec("open-webui", "Open WebUI", [], "Open WebUI", ["ai-models", "ai-agents", "selfhost"],
        "LLM web UI", ["Self-hosted interface for many models", "private chat", "RAG chat"],
        "open source", "BSD-3-Clause", "open-webui/open-webui",
        ["web", "local", "api"], ["local", "self-hosted", "cloud"], "free",
        ["docker", "local installation"], ["developer", "technical team"],
        "Intermediate", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, False, True,
        "free", "Users who want a private, self-hosted ChatGPT-like UI.",
        "Users who prefer a fully managed hosted service.",
        "LibreChat, text-generation-webui.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/ai-machine-learning"},
         {"name": "GitHub", "url": "https://github.com/open-webui/open-webui"}])),

    # ============ Note-taking / Knowledge (AlternativeTo: Notion family) ============
    a(rec("notion", "Notion", [], "Notion Labs", ["prod-notes", "prod-docs", "business"],
        "All-in-one workspace", ["Notes", "databases", "docs", "project tracking"],
        "proprietary", "Proprietary", None,
        ["web", "desktop", "mobile", "android", "ios"], ["cloud"], "freemium",
        ["account required"], ["entrepreneur", "creator", "beginner", "team"],
        "Beginner", "Instant", "None", "None", "None", "High",
        False, False, True, True, True, True, True, True, True, False, True,
        "freemium", "Teams wanting a flexible all-in-one workspace with minimal setup.",
        "Users wanting full data control or offline/local use.",
        "Obsidian, AppFlowy, Outline, AFFiNE.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/notion"},
         {"name": "AlternativeTo", "url": "https://alternativeto.net/software/notion/"}])),

    a(rec("obsidian", "Obsidian", [], "Obsidian", ["prod-notes", "selfhost"],
        "Note-taking app", ["Non-linear notes", "knowledge graph", "wiki-style linking", "markdown"],
        "proprietary", "Proprietary", None,
        ["desktop", "mobile", "android", "ios", "local"], ["local", "cloud"], "freemium",
        ["local installation", "account optional"], ["creator", "researcher", "developer", "beginner"],
        "Beginner", "Very low", "Minimal", "None", "Low", "High",
        False, False, True, True, True, True, True, True, True, False, True,
        "freemium", "Users wanting markdown notes with local storage and linking.",
        "Users wanting real-time multi-user collaboration.",
        "AppFlowy, Logseq, Obsidian (Proprietary).",
        [{"name": "AlternativeTo", "url": "https://alternativeto.net/software/notion/"},
         {"name": "Official", "url": "https://obsidian.md"}],
        "Proprietary but free for personal use; verify pricing model.")),

    a(rec("appflowy", "AppFlowy", [], "AppFlowy", ["prod-notes", "selfhost", "open-source"],
        "Open-source workspace", ["Data control", "notion-like workspace", "local-first"],
        "open source", "AGPL-3.0", "AppFlowy-IO/AppFlowy",
        ["desktop", "mobile", "android", "ios", "local", "web"], ["local", "self-hosted", "cloud"],
        "freemium",
        ["local installation", "build tools", "account optional"], ["developer", "creator", "beginner"],
        "Beginner", "Medium", "Minimal", "Guided", "Moderate", "High",
        True, False, False, True, True, True, True, True, True, False, True,
        "freemium", "Users who want a Notion-like tool with local data control.",
        "Users wanting smooth no-build native experience.",
        "Notion, Obsidian, AFFiNE.",
        [{"name": "AlternativeTo", "url": "https://alternativeto.net/software/notion/"},
         {"name": "GitHub", "url": "https://github.com/AppFlowy-IO/AppFlowy"}])),

    a(rec("privacynotes", "PrivacyNotes", [], "PrivacyNotes", ["prod-notes", "privacy", "selfhost"],
        "Encrypted workspace", ["E2E encrypted notes", "zero-knowledge", "password manager", "file storage"],
        "open source", "AGPL-3.0", None,
        ["web", "desktop", "mobile", "android", "ios"], ["cloud"], "freemium",
        ["account required"], ["beginner", "privacy-focused"],
        "Beginner", "Instant", "None", "None", "None", "Moderate",
        True, False, True, True, True, True, True, True, True, False, True,
        "freemium", "Privacy-focused users who want encrypted note-taking.",
        "Power users needing offline-only/local sync.",
        "Obsidian, Standard Notes, Joplin.",
        [{"name": "AlternativeTo", "url": "https://alternativeto.net/software/notion/"}],
        "Repo/license to verify.")),

    a(rec("logseq", "Logseq", [], "Logseq", ["prod-notes", "session"], "Outliner tool",
        ["Outliner", "PKM", "graphs"],
        "open source", "AGPL-3.0", "logseq/logseq",
        ["desktop", "mobile", "local"], ["local", "cloud"], "free",
        ["local installation"], ["researcher", "creator", "developer"],
        "Beginner+", "Low", "Minimal", "None", "Low", "High",
        True, False, False, True, True, True, True, True, True, False, True,
        "free", "PKM users who prefer bullet outliners and local-first data.",
        "Teams wanting centralized real-time collaboration.",
        "Obsidian, AppFlowy, Notion.",
        [{"name": "GitHub", "url": "https://github.com/logseq/logseq"}], "Verify activity.")),

    # ============ Automation / No-code ============
    a(rec("n8n", "n8n", ["n8n.io"], "n8n", ["prod-automation", "dev", "selfhost", "data-etl"],
        "Workflow automation", ["Visual workflows", "500+ app integrations", "AI agents", "code"],
        "open source", "Sustainable Use License", "n8n-io/n8n",
        ["web", "local", "api"], ["cloud", "local", "self-hosted"], "freemium",
        ["docker", "local installation"], ["developer", "technical team"],
        "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Developers who want self-hosted, code-flexible automation.",
        "Non-technical users wanting pure no-code with hosted reliability.",
        "Zapier, Make, Activepieces.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/developer-tools"},
         {"name": "GitHub", "url": "https://github.com/n8n-io/n8n"}])),

    a(rec("activepieces", "Activepieces", [], "Activepieces", ["prod-automation", "selfhost"],
        "Automation platform", ["No-code automation like Zapier", "self-hosted"],
        "open source", "MIT", "activepieces/activepieces",
        ["web", "local"], ["cloud", "local", "self-hosted"], "free",
        ["docker", "local installation"], ["beginner", "technical team"],
        "Beginner", "Low", "None", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Users wanting a self-hosted Zapier alternative.",
        "Users needing heavily code-first automation.",
        "n8n, Zapier, Make.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/activepieces/activepieces"}])),

    # ============ Databases / Storage (StackShare, Infra) ============
    a(rec("postgres", "PostgreSQL", ["postgres"], "PostgreSQL Global Development Group",
        ["dev-backend", "infra-storage", "dev"], "Relational database",
        ["relational DB", "backend storage", "SQL", "primary data store"],
        "open source", "PostgreSQL License", "postgres/postgres",
        ["server", "api"], ["local", "self-hosted", "cloud"], "free",
        ["docker", "local installation", "database required", "sql"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "Manual", "High", "Very high",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Developers requiring a robust open-source SQL database.",
        "Users wanting a fully managed zero-ops database.",
        "MySQL, SQLite, MongoDB.",
        [{"name": "StackShare", "url": "https://stackshare.io/"},
         {"name": "GitHub", "url": "https://github.com/postgres/postgres"}])),

    a(rec("sqlite", "SQLite", [], "sqlite.org", ["dev-backend", "dev"], "Embedded database",
        ["embedded SQL DB", "local apps", "no server"],
        "open source", "Public Domain", None,
        ["desktop", "mobile", "api"], ["local"], "free",
        ["local installation", "build tools"], ["developer"],
        "Intermediate", "Instant", "Developer-oriented", "None", "Low", "Limited",
        True, False, False, True, False, False, True, True, True, True, True,
        "free", "Developers needing a simple embedded database for local apps/mobile.",
        "Multi-writer/cloud-scale production systems.",
        "PostgreSQL, MongoDB, DuckDB.",
        [{"name": "StackShare", "url": "https://stackshare.io/"}, {"name": "Official", "url": "https://sqlite.org"}])),

    a(rec("supabase", "Supabase", [], "Supabase", ["dev-backend", "infra-storage", "dev", "selfhost"],
        "Backend-as-a-service", ["Postgres-powered backend", "auth", "APIs", "storage", "realtime", "vector"],
        "open source", "Apache-2.0", "supabase/supabase",
        ["web", "api"], ["cloud", "local", "self-hosted"], "freemium",
        ["docker", "api keys", "sql"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "One-click", "Moderate", "High",
        True, False, True, False, True, True, False, False, False, True, True,
        "freemium", "Developers who want Firebase-like features on open-source Postgres.",
        "Non-developers wanting zero-code.",
        "Firebase, PocketBase, Appwrite.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/developer-tools"},
         {"name": "GitHub", "url": "https://github.com/supabase/supabase"}])),

    a(rec("firebase", "Firebase", [], "Google", ["dev-backend", "dev"], "Backend-as-a-service",
        ["Google backend", "auth", "realtime DB", "hosting", "analytics"],
        "proprietary", "Proprietary", None,
        ["web", "mobile"], ["cloud"], "freemium",
        ["account required", "api keys"], ["developer"],
        "Intermediate", "Low", "Moderate", "None", "Low", "Moderate",
        False, False, True, False, False, True, True, True, True, True, True,
        "freemium", "Developers who want a managed Google backend with generous free tier.",
        "Users wanting vendor independence/self-hosting.",
        "Supabase, Appwrite, PocketBase.",
        [{"name": "Capterra", "url": "https://www.capterra.com/"}, {"name": "Official", "url": "https://firebase.google.com"}])),

    # ============ Frontend / Dev frameworks ============
    a(rec("react", "React", ["reactjs"], "Meta", ["dev-frameworks", "dev"], "JS library",
        ["UI library", "component-based frontend", "SPA"],
        "open source", "MIT", "facebook/react",
        ["web", "mobile"], ["local", "cloud"], "free",
        ["node", "npm", "build tools"], ["developer"],
        "Intermediate", "Medium", "Developer-oriented", "Manual", "Moderate", "Very high",
        True, False, False, True, False, True, True, True, True, False, True,
        "free", "Developers building interactive web UIs.",
        "Absolute beginners wanting no tooling.",
        "Vue, Svelte, Angular.",
        [{"name": "StackShare", "url": "https://stackshare.io/"}, {"name": "GitHub", "url": "https://github.com/facebook/react"}])),

    a(rec("nextjs", "Next.js", [], "Vercel", ["dev-frameworks", "dev", "dev-devops"], "Full-stack framework",
        ["React full-stack", "SSR/SSG", "web apps", "API routes"],
        "open source", "MIT", "vercel/next.js",
        ["web", "api"], ["cloud", "local", "self-hosted"], "free",
        ["node", "npm", "build tools", "dev environment"], ["developer"],
        "Intermediate", "Medium", "Developer-oriented", "Guided", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Developers building production React web apps.",
        "Beginners wanting a hosted visual builder.",
        "Vue/Nuxt, SvelteKit, Remix.",
        [{"name": "StackShare", "url": "https://stackshare.io/"}, {"name": "GitHub", "url": "https://github.com/vercel/next.js"}])),

    a(rec("expo", "Expo", [], "Expo", ["dev-mobile", "dev-frameworks", "dev"], "Mobile dev framework",
        ["React Native development", "mobile apps", "easy device testing"],
        "open source", "MIT", "expo/expo",
        ["web", "mobile", "local"], ["local", "cloud"], "free",
        ["node", "npm", "build tools"], ["developer"],
        "Intermediate", "Low", "Developer-oriented", "Guided", "Moderate", "High",
        True, False, False, True, True, True, True, True, True, False, True,
        "free", "Developers building cross-platform mobile apps with fast device testing.",
        "Developers needing deep native modules/Android Studio control.",
        "React Native, Flutter, native Android.",
        [{"name": "GitHub", "url": "https://github.com/expo/expo"}],
        "Crucial for the mobile/test-on-device decision.")),

    a(rec("flutter", "Flutter", [], "Google", ["dev-mobile", "dev-frameworks"], "Mobile UI framework",
        ["Cross-platform native UI", "iOS/Android/web/desktop", "Dart"],
        "open source", "BSD-3-Clause", "flutter/flutter",
        ["mobile", "desktop", "web"], ["local", "cloud"], "free",
        ["SDK", "build tools", "dev environment"], ["developer"],
        "Advanced", "Medium", "Deep developer involvement", "Manual", "Moderate", "Very high",
        True, False, False, True, True, True, True, True, True, True, True,
        "free", "Developers who want high-performance cross-platform native UI.",
        "Beginners wanting minimal coding.",
        "React Native, Expo, Ionic.",
        [{"name": "GitHub", "url": "https://github.com/flutter/flutter"}])),

    # ============ Design ============
    a(rec("figma", "Figma", [], "Figma", ["design-uiux", "design"], "Design tool",
        ["UI design", "collaborative prototyping", "design system"],
        "proprietary", "Proprietary", None,
        ["web", "desktop"], ["cloud"], "freemium",
        ["account required"], ["designer", "entrepreneur", "team"],
        "Beginner", "Instant", "None", "None", "None", "High",
        False, False, True, False, False, True, False, False, False, False, False,
        "freemium", "Designers wanting collaborative cloud UI design.",
        "Users wanting self-hosted, offline design.",
        "Penpot, Figma (Proprietary), Sketch.",
        [{"name": "StackShare", "url": "https://stackshare.io/"}, {"name": "Capterra", "url": "https://www.capterra.com/"}])),

    a(rec("penpot", "Penpot", [], "Penpot", ["design-uiux", "design", "selfhost"],
        "Design tool (open source)", ["UI design", "prototyping", "open-source design system"],
        "open source", "MPL-2.0", "penpot/penpot",
        ["web", "local"], ["cloud", "local", "self-hosted"], "free",
        ["docker"], ["designer", "technical team"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, False, False,
        "free", "Designers who want an open-source Figma alternative.",
        "Users needing Adobe CC vector workflows.",
        "Figma, Inkscape, generic.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/misc"},
         {"name": "GitHub", "url": "https://github.com/penpot/penpot"}])),

    # ============ Video / Creative ============
    a(rec("capcut", "CapCut", [], "ByteDance", ["design-video", "design"], "Video editor",
        ["easy video editing", "social media", "templates"],
        "proprietary", "Proprietary", None,
        ["web", "mobile", "desktop"], ["cloud", "local"], "freemium",
        ["account required"], ["creator", "beginner"],
        "Beginner", "Instant", "None", "None", "None", "Moderate",
        False, False, True, False, False, True, True, True, True, False, False,
        "freemium", "Creators who want a simple, quick video editor.",
        "Users wanting privacy or open-source control.",
        "OpenCut, DaVinci Resolve, Kdenlive.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/capcut"}])),

    a(rec("opencut", "OpenCut", [], "OpenCut", ["design-video", "design", "selfhost"],
        "Video editor (browser)", ["browser video editor", "privacy", "no install"],
        "open source", "MIT", "OpenCut-app/OpenCut",
        ["web", "local"], ["cloud", "self-hosted"], "free",
        ["docker", "build tools"], ["creator"],
        "Beginner+", "Low", "Minimal", "Guided", "Moderate", "Moderate",
        True, False, False, True, True, True, False, False, False, False, False,
        "free", "Creators who want a self-hosted browser video editor.",
        "Users needing pro-grade timeline editing.",
        "CapCut, DaVinci Resolve, Kdenlive, Shotcut.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/misc"},
         {"name": "GitHub", "url": "https://github.com/OpenCut-app/OpenCut"}])),

    a(rec("kdenlive", "Kdenlive", [], "KDE", ["design-video", "design", "selfhost"],
        "Video editor (desktop)", ["desktop video editor", "open-source", "timeline"],
        "open source", "GPL-2.0", "KDE/kdenlive",
        ["desktop", "local"], ["local"], "free",
        ["local installation"], ["creator"],
        "Intermediate", "Low", "Minimal", "None", "Moderate", "High",
        True, False, False, True, False, False, True, False, False, False, False,
        "free", "Creators who want a free, powerful desktop video editor.",
        "Users wanting cloud/browser editing.",
        "OpenCut, DaVinci Resolve, CapCut.",
        [{"name": "GitHub", "url": "https://github.com/KDE/kdenlive"}])),

    # ============ Project management / Business ============
    a(rec("monday", "monday.com", [], "Monday", ["biz-pm", "business"], "Work OS",
        ["project management", "team planning", "workflows"],
        "proprietary", "Proprietary", None,
        ["web", "mobile", "desktop"], ["cloud"], "subscription",
        ["account required"], ["team", "enterprise", "entrepreneur"],
        "Beginner", "Instant", "None", "None", "None", "High",
        False, False, True, False, False, True, True, True, True, True, True,
        "subscription", "Teams wanting a flexible, collaborative work OS.",
        "Budget-conscious or self-hosting users.",
        "Airtable, ClickUp, Baserow.",
        [{"name": "Capterra", "url": "https://www.capterra.com/p/147657/monday-com/"}])),

    a(rec("clickup", "ClickUp", [], "ClickUp", ["biz-pm", "business"], "Project management",
        ["all-in-one project mgmt", "tasks", "docs", "goals"],
        "proprietary", "Proprietary", None,
        ["web", "mobile", "desktop"], ["cloud"], "freemium",
        ["account required"], ["team", "entrepreneur"],
        "Beginner", "Instant", "None", "None", "None", "High",
        False, False, True, False, False, True, True, True, True, True, True,
        "freemium", "Teams wanting feature-rich project management.",
        "Minimalists or self-hosters.",
        "Monday, Airtable, Focalboard.",
        [{"name": "Capterra", "url": "https://www.capterra.com/"}])),

    a(rec("focalboard", "Focalboard", [], "Mattermost", ["biz-pm", "selfhost", "open-source"],
        "Kanban/PM (open source)", ["self-hosted kanban", "project boards", "mattermost"],
        "open source", "MPL-2.0", "mattermost/focalboard",
        ["web", "desktop", "mobile"], ["local", "self-hosted"], "free",
        ["docker", "local installation"], ["technical team"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "Moderate",
        True, False, False, True, True, True, True, True, True, False, True,
        "free", "Teams wanting a self-hosted Trello-like boards tool.",
        "Users wanting heavy automation.",
        "Trello, ClickUp, Kanboard.",
        [{"name": "GitHub", "url": "https://github.com/mattermost/focalboard"}])),

    # ============ Communication / Collaboration ============
    a(rec("slack", "Slack", [], "Salesforce", ["prod-docs", "prod-email", "business"], "Team chat",
        ["team messaging", "channels", "integrations"],
        "proprietary", "Proprietary", None,
        ["web", "desktop", "mobile"], ["cloud"], "freemium",
        ["account required"], ["team", "enterprise"],
        "Beginner", "Instant", "None", "None", "None", "Moderate",
        False, False, True, False, False, True, True, True, True, True, True,
        "freemium", "Teams who want hosted, reliable team chat.",
        "Users wanting self-hosting or full data control.",
        "Mattermost, Rocket.Chat, Zulip.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/discord"},
         {"name": "Capterra", "url": "https://www.capterra.com/"}])),

    a(rec("mattermost", "Mattermost", [], "Mattermost", ["prod-docs", "prod-email", "selfhost"],
        "Team chat (open source)", ["secure collaboration", "self-hosted", "enterprise"],
        "open source", "proprietary-core", "mattermost/mattermost",
        ["web", "desktop", "mobile"], ["local", "self-hosted", "cloud"], "freemium",
        ["docker", "local installation"], ["technical team", "enterprise"],
        "Intermediate", "Medium", "Moderate", "Guided", "Moderate", "High",
        True, False, False, True, True, True, True, True, True, True, True,
        "freemium", "Enterprises needing secure, self-hosted team chat.",
        "Small teams wanting zero-ops hosting.",
        "Slack, Rocket.Chat, Zulip.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/security-privacy"},
         {"name": "GitHub", "url": "https://github.com/mattermost/mattermost"}])),

    a(rec("signal", "Signal", [], "Signal Foundation", ["prod-email", "infra-security", "selfhost-mobile"],
        "Secure messaging", ["E2E encrypted messaging", "privacy", "open source client"],
        "open source", "AGPL-3.0", "signalapp/Signal-Android",
        ["mobile", "desktop"], ["cloud"], "free",
        ["account required", "phone number"], ["privacy-focused", "beginner"],
        "Beginner", "Instant", "None", "None", "None", "Limited",
        True, False, True, False, False, False, True, True, True, True, True,
        "free", "Users prioritizing end-to-end encrypted messaging.",
        "Users needing self-hosted servers or team collaboration.",
        "Element, Session, Telegram.",
        [{"name": "F-Droid", "url": "https://f-droid.org/"}, {"name": "GitHub", "url": "https://github.com/signalapp/Signal-Android"}])),

    a(rec("element", "Element", [], "Element", ["prod-docs", "prod-email", "selfhost-mobile", "selfhost"],
        "Matrix client", ["Matrix", "decentralized", "E2E encrypted", "self-hosted"],
        "open source", "Apache-2.0", "element-hq/element-web",
        ["web", "desktop", "mobile"], ["cloud", "self-hosted"], "freemium",
        ["account required"], ["technical team", "privacy-focused"],
        "Intermediate", "Low", "Minimal", "None", "Low", "High",
        True, False, True, True, True, True, True, True, True, True, True,
        "freemium", "Users/teams wanting decentralized, self-hostable messaging.",
        "Users wanting the simplest zero-setup chat.",
        "Signal, Slack, Rocket.Chat.",
        [{"name": "F-Droid", "url": "https://f-droid.org/"}, {"name": "GitHub", "url": "https://github.com/element-hq/element-web"}])),

    # ============ Marketing / SEO ============
    a(rec("openseo", "OpenSEO", ["openseo"], "OpenSEO", ["biz-marketing", "selfhost", "data-etl"],
        "SEO platform (self-hosted)", ["keyword research", "backlink analysis", "rank tracking"],
        "open source", "MIT", None,
        ["web", "local"], ["cloud", "self-hosted"], "free",
        ["docker", "api keys", "build tools"], ["technical team", "developer"],
        "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Marketing teams wanting self-hosted SEO tooling.",
        "Non-technical users wanting a hosted SEO suite.",
        "Semrush, Ahrefs, Screaming Frog.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/business-software"}])),

    # ============ Analytics / BI ============
    a(rec("superset", "Apache Superset", [], "Apache", ["data-bi", "data", "selfhost"],
        "BI tool", ["data exploration", "dashboards", "SQL"],
        "open source", "Apache-2.0", "apache/superset",
        ["web", "local"], ["self-hosted", "cloud"], "free",
        ["docker", "python", "database"], ["technical team", "developer", "analyst"],
        "Intermediate", "Medium", "Developer-oriented", "One-click", "High", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Analysts who want a powerful open-source BI tool.",
        "Beginners wanting a simple hosted dashboard.",
        "Metabase, Grafana, Power BI.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/data-analytics"},
         {"name": "GitHub", "url": "https://github.com/apache/superset"}])),

    a(rec("metabase", "Metabase", [], "Metabase", ["data-bi", "data", "selfhost"],
        "BI/analytics", ["self-serve analytics", "dashboards", "non-technical BI"],
        "open source", "AGPL-3.0", "metabase/metabase",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker", "database"], ["technical team", "analyst", "team"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Non-developers who want friendly, self-hosted analytics.",
        "Developers needing deep chart/plugin control.",
        "Superset, Grafana, Looker.",
        [{"name": "GitHub", "url": "https://github.com/metabase/metabase"}])),

    a(rec("grafana", "Grafana", [], "Grafana Labs", ["infra-monitoring", "infra", "data-bi"],
        "Observability/BI", ["unified observability", "metrics/logs/traces", "dashboards"],
        "open source", "AGPL-3.0", "grafana/grafana",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker", "database"], ["technical team", "developer", "analyst"],
        "Intermediate", "Low", "Moderate", "One-click", "Moderate", "Very high",
        True, False, False, True, True, True, False, False, False, False, False,
        "freemium", "Teams needing flexible monitoring/dashboarding.",
        "Non-technical users wanting pre-built BI reports.",
        "Metabase, Prometheus, Power BI.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/infrastructure-operations"},
         {"name": "GitHub", "url": "https://github.com/grafana/grafana"}])),

    # ============ Scraping ============
    a(rec("firecrawl", "Firecrawl", [], "Firecrawl", ["data-scraping", "data", "ai-ml-infra"],
        "Web scraping API", ["scrape to markdown/JSON", "AI-ready data"],
        "open source", "AGPL-3.0", "mendableai/firecrawl",
        ["web", "api"], ["cloud", "self-hosted"], "freemium",
        ["api keys", "node/python"], ["developer", "technical team"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, True, False, True, True, False, False, False, True, True,
        "freemium", "Developers who want clean AI-ready scraping via API.",
        "Users needing precise browser automation control.",
        "Crawl4AI, Scrapy, Apify.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/data-analytics"},
         {"name": "GitHub", "url": "https://github.com/mendableai/firecrawl"}])),

    a(rec("scrapy", "Scrapy", [], "Scrapy", ["data-scraping", "data"], "Web scraping framework",
        ["python scraping", "crawling", "pipelines"],
        "open source", "BSD-3-Clause", "scrapy/scrapy",
        ["api"], ["local", "self-hosted"], "free",
        ["python", "pip", "build tools", "developer"], ["developer"],
        "Advanced", "Medium", "Deep developer involvement", "Manual", "High", "Very high",
        True, False, False, True, False, False, False, False, False, True, True,
        "free", "Developers building custom scraping pipelines.",
        "Non-developers wanting an instant hosted scraper.",
        "Firecrawl, Crawl4AI, Apify.",
        [{"name": "GitHub", "url": "https://github.com/scrapy/scrapy"}])),

    # ============ Monitoring / Uptime ============
    a(rec("uptime-kuma", "Uptime Kuma", [], "Uptime Kuma", ["infra-monitoring", "infra", "selfhost"],
        "Uptime monitor", ["self-hosted uptime monitoring", "status pages"],
        "open source", "MIT", "louislam/uptime-kuma",
        ["web", "local"], ["self-hosted"], "free",
        ["docker"], ["technical team", "developer"],
        "Beginner+", "Instant", "Minimal", "One-click", "Low", "Moderate",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Anyone who wants a simple self-hosted uptime monitor.",
        "Users wanting SaaS monitoring with alerting SLAs.",
        "Grafana, Statuspage, Healthchecks.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/infrastructure-operations"},
         {"name": "GitHub", "url": "https://github.com/louislam/uptime-kuma"}])),

    a(rec("healthchecks", "Healthchecks", [], "Healthchecks", ["infra-monitoring", "infra", "selfhost"],
        "Cron monitoring", ["monitor scheduled jobs", "self-hosted"],
        "open source", "BSD-3-Clause", "healthchecks/healthchecks",
        ["web", "local"], ["self-hosted"], "free",
        ["docker", "python"], ["technical team", "developer"],
        "Beginner+", "Low", "Minimal", "One-click", "Low", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Developers who want to monitor cron/scheduled jobs.",
        "Users needing full site/API uptime dashboards.",
        "Uptime Kuma, Grafana, cronitor.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/healthchecks/healthchecks"}])),

    # ============ Password / Security / Privacy ============
    a(rec("bitwarden", "Bitwarden", [], "Bitwarden", ["infra-security", "security", "selfhost"],
        "Password manager", ["cross-platform pswd manager", "self-hostable", "open source"],
        "open source", "GPL-3.0", "bitwarden/server",
        ["web", "desktop", "mobile"], ["cloud", "self-hosted"], "freemium",
        ["account required", "docker"], ["privacy-focused", "beginner", "team"],
        "Beginner", "Low", "Minimal", "Guided", "Low", "High",
        True, False, True, False, True, True, True, True, True, True, True,
        "freemium", "Users who want an open-source, self-hostable password manager.",
        "Users wanting an offline-only local vault.",
        "KeePass, 1Password, Bitwarden.",
        [{"name": "F-Droid", "url": "https://f-droid.org/"}, {"name": "GitHub", "url": "https://github.com/bitwarden/server"}])),

    a(rec("keycloak", "Keycloak", [], "Red Hat", ["infra-security", "dev-backend", "selfhost"],
        "IAM", ["single sign-on", "auth", "identity management"],
        "open source", "Apache-2.0", "keycloak/keycloak",
        ["web", "server"], ["self-hosted"], "free",
        ["docker", "java", "database"], ["technical team", "enterprise"],
        "Advanced", "High", "Deep developer involvement", "Manual", "High", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Enterprises needing self-hosted SSO/IAM.",
        "Small teams wanting a hosted auth provider.",
        "Auth0, Authentik, Ory.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/security-privacy"},
         {"name": "GitHub", "url": "https://github.com/keycloak/keycloak"}])),

    a(rec("authentik", "Authentik", [], "Authentik", ["infra-security", "identity", "selfhost"],
        "IAM/SSO", ["self-hosted identity", "SSO", "MFA"],
        "open source", "MIT", "goauthentik/authentik",
        ["web", "server"], ["self-hosted"], "free",
        ["docker", "database"], ["technical team", "enterprise"],
        "Advanced", "High", "Deep developer involvement", "Manual", "High", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Enterprises wanting a modern self-hosted identity provider.",
        "Small apps wanting a drop-in hosted provider.",
        "Keycloak, Auth0, Ory.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/goauthentik/authentik"}])),

    # ============ Media / Photos ============
    a(rec("immich", "Immich", [], "Immich", ["infra-storage", "selfhost", "design-video"],
        "Photo backup", ["self-hosted photo/video backup", "local library", "AI search"],
        "open source", "AGPL-3.0", "immich-app/immich",
        ["web", "mobile"], ["self-hosted"], "free",
        ["docker"], ["technical team", "privacy-focused"],
        "Intermediate", "Medium", "Moderate", "One-click", "High", "High",
        True, False, False, True, True, True, False, True, True, False, False,
        "free", "Users who want to self-host their photo library.",
        "Users wanting Google Photos-like cloud convenience.",
        "Nextcloud, PhotoPrism, Syncthing.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/infrastructure-operations"},
         {"name": "GitHub", "url": "https://github.com/immich-app/immich"}])),

    a(rec("nextcloud", "Nextcloud", [], "Nextcloud", ["prod-docs", "prod-notes", "infra-storage", "selfhost"],
        "File sync & collaboration", ["self-hosted files", "office suite", "calendar", "contacts"],
        "open source", "AGPL-3.0", "nextcloud/server",
        ["web", "desktop", "mobile"], ["self-hosted"], "free",
        ["docker", "php", "database"], ["technical team", "privacy-focused"],
        "Intermediate", "Medium", "Moderate", "Guided", "High", "Very high",
        True, False, False, True, True, True, True, True, True, True, True,
        "freemium", "Users/teams who want a self-hosted Google Workspace replacement.",
        "Users wanting a simple hosted file share.",
        "Google Drive, ownCloud, FileRun.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/nextcloud/server"}])),

    a(rec("jellyfin", "Jellyfin", [], "Jellyfin", ["infra-storage", "selfhost", "design-video"],
        "Media server", ["self-hosted media server", "movies/music"],
        "open source", "GPL-2.0", "jellyfin/jellyfin",
        ["web", "desktop", "mobile"], ["self-hosted"], "free",
        ["docker"], ["technical team", "privacy-focused"],
        "Intermediate", "Medium", "Moderate", "One-click", "High", "High",
        True, False, False, True, True, True, True, True, True, False, False,
        "free", "Users who want to self-host a media library server.",
        "Users wanting a simple streaming subscription.",
        "Plex, Emby, Kodi.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/misc"},
         {"name": "GitHub", "url": "https://github.com/jellyfin/jellyfin"}])),

    # ============ Self-hosted docs/wiki ============
    a(rec("outline", "Outline", [], "Outline", ["prod-notes", "prod-docs", "selfhost"],
        "Wiki/knowledge base", ["team wiki", "real-time collaboration", "self-hosted"],
        "open source", "BUSL-1.1", "outline/outline",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker", "database"], ["technical team", "team"],
        "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Teams wanting a clean self-hosted knowledge base.",
        "Non-technical users wanting a hosted wiki.",
        "Notion, BookStack, Wiki.js.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/content-publishing"},
         {"name": "GitHub", "url": "https://github.com/outline/outline"}])),

    a(rec("bookstack", "BookStack", [], "BookStack", ["prod-notes", "prod-docs", "selfhost"],
        "Wiki/documentation", ["self-hosted wiki", "documentation", "book-like"],
        "open source", "MIT", "BookStackApp/BookStack",
        ["web", "local"], ["self-hosted"], "free",
        ["docker", "php", "mysql"], ["technical team", "developer"],
        "Intermediate", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, False, False,
        "free", "Teams wanting a straightforward self-hosted documentation wiki.",
        "Teams needing real-time collaborative editing.",
        "Outline, Wiki.js, Confluence.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/BookStackApp/BookStack"}])),

    # ============ IDE / editors ============
    a(rec("vscode", "Visual Studio Code", ["vscode"], "Microsoft", ["dev-ide", "dev"],
        "Code editor", ["code editing", "extensions", "debugging"],
        "open source", "MIT", "microsoft/vscode",
        ["desktop", "web"], ["local", "cloud"], "free",
        ["local installation"], ["developer"],
        "Intermediate", "Very low", "Developer-oriented", "None", "Low", "Very high",
        True, False, False, True, True, True, True, False, False, True, True,
        "free", "Developers who want a flexible, extensible code editor.",
        "Users wanting a fully AI-agentic coding experience.",
        "Cursor, JetBrains, Zed.",
        [{"name": "GitHub", "url": "https://github.com/microsoft/vscode"}])),

    # ============ CRM ============
    a(rec("twenty", "Twenty", [], "Twenty", ["biz-crm", "business", "selfhost", "open-source"],
        "CRM (open source)", ["modern CRM", "sales pipelines", "self-hosted"],
        "open source", "AGPL-3.0", "twentyhq/twenty",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker", "postgres"], ["technical team", "sales"],
        "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Sales teams wanting an open-source modern CRM.",
        "Enterprises needing mature BI/ecosystem.",
        "HubSpot, Salesforce, SuiteCRM.",
        [{"name": "GitHub", "url": "https://github.com/twentyhq/twenty"}])),

    a(rec("suitecrm", "SuiteCRM", [], "SuiteCRM", ["biz-crm", "business", "selfhost"],
        "CRM (open source)", ["mature CRM", "sales", "self-hosted"],
        "open source", "AGPL-3.0", "salesagility/SuiteCRM",
        ["web", "local"], ["self-hosted"], "free",
        ["docker", "php", "mysql"], ["technical team", "enterprise"],
        "Intermediate", "High", "Moderate", "Manual", "High", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Enterprises wanting a mature, extensible self-hosted CRM.",
        "Small teams wanting quick setup.",
        "Twenty, HubSpot, EspoCRM.",
        [{"name": "GitHub", "url": "https://github.com/salesagility/SuiteCRM"}])),

    # ============ AI models (open weight distinction) ============
    a(rec("qwen", "Qwen", ["qwen3"], "Alibaba", ["ai-models"], "Open-weight LLM",
        ["multilingual LLM", "open weights", "chat/agent"],
        "open weight", "Apache-2.0 (weights)", "QwenLM/Qwen3",
        ["api"], ["cloud", "local"], "free",
        ["api keys", "gpu", "model download"], ["developer", "researcher"],
        "Advanced", "High", "Deep developer involvement", "Manual", "High", "High",
        False, True, True, False, True, False, False, False, False, True, True,
        "free", "Developers/researchers wanting strong open-weight multilingual models.",
        "Users wanting zero-ops hosted chat.",
        "Llama, DeepSeek, Gemma.",
        [{"name": "Hugging Face", "url": "https://huggingface.co/Qwen"}] )),

    a(rec("llama", "Llama", ["llama3"], "Meta", ["ai-models"], "Open-weight LLM",
        ["open weights LLM", "chat", "fine-tune"],
        "open weight", "Llama Community License", "meta-llama/llama-models",
        ["api"], ["cloud", "local"], "free",
        ["api keys", "gpu"], ["developer", "researcher"],
        "Advanced", "High", "Deep developer involvement", "Manual", "High", "High",
        False, True, True, False, True, False, False, False, False, True, True,
        "free", "Developers who want a widely-supported open-weight model.",
        "Users wanting a fully permissive OS license (vs weights).",
        "Qwen, DeepSeek, Mistral.",
        [{"name": "Hugging Face", "url": "https://huggingface.co/meta-llama"}] )),

    a(rec("mistral", "Mistral", [], "Mistral AI", ["ai-models", "ai-ml-infra"], "LLM/open weight",
        ["open-weight models", "fine-tune", "api"],
        "open weight", "Apache-2.0 / commercial", "mistralai/mistral-src",
        ["api", "web"], ["cloud", "local"], "freemium",
        ["api keys", "gpu"], ["developer", "researcher","enterprise"],
        "Intermediate", "Medium", "Developer-oriented", "Guided", "Low", "Moderate",
        False, True, True, False, True, False, False, False, False, True, True,
        "freemium", "Developers wanting strong European open-weight models.",
        "Users wanting only fully open-source OS-licensed weights.",
        "Qwen, Llama, Claude.",
        [{"name": "Hugging Face", "url": "https://huggingface.co/mistralai"}] )),

    a(rec("transformers", "Transformers", ["HF transformers"], "Hugging Face", ["ai-models", "ai-ml-infra"],
        "ML library", ["state-of-the-art models", "PyTorch", "hub"],
        "open source", "Apache-2.0", "huggingface/transformers",
        ["api"], ["local", "cloud"], "free",
        ["python", "pip", "gpu"], ["developer", "researcher"],
        "Advanced", "Medium", "Deep developer involvement", "Manual", "Moderate", "Very high",
        True, True, False, True, True, False, False, False, False, True, True,
        "free", "Developers/researchers building with cutting-edge transformer models.",
        "Users wanting a point-and-click model app.",
        "vLLM, Ollama, LangChain.",
        [{"name": "Hugging Face", "url": "https://huggingface.co/docs/transformers"},
         {"name": "GitHub", "url": "https://github.com/huggingface/transformers"}])),

    # ============ Dev frameworks: no-code SaaS ============
    a(rec("airtable", "Airtable", [], "Airtable", ["biz-pm", "business"], "No-code database",
        ["relational no-code", "apps", "databases"],
        "proprietary", "Proprietary", None,
        ["web", "mobile"], ["cloud"], "freemium",
        ["account required"], ["team", "entrepreneur", "beginner"],
        "Beginner", "Instant", "None", "None", "None", "High",
        False, False, True, False, False, True, True, True, True, True, True,
        "freemium", "Non-technical teams wanting flexible no-code databases.",
        "Developers wanting source control/self-hosting.",
        "Baserow, NocoDB, monday.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/alternatives/notion"},
         {"name": "Capterra", "url": "https://www.capterra.com/"}])),

    a(rec("baserow", "Baserow", [], "Baserow", ["biz-pm", "business", "selfhost"],
        "No-code database (open source)", ["no-code database", "self-hosted", "apps"],
        "open source", "MIT", "baserow/baserow",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker", "postgres"], ["technical team", "team"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Teams wanting an open-source Airtable alternative.",
        "Teams needing deep marketing/ERP workflows.",
        "Airtable, NocoDB, monday.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/business-software"},
         {"name": "GitHub", "url": "https://github.com/baserow/baserow"}])),

    a(rec("nocodb", "NocoDB", [], "NocoDB", ["biz-pm", "business", "selfhost"],
        "No-code DB (open source)", ["spreadsheet UI over SQL", "self-hosted"],
        "open source", "AGPL-3.0", "nocodb/nocodb",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker"], ["technical team", "developer"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Developers wanting a no-code UI over an existing database.",
        "Users wanting a fully turnkey hosted SaaS.",
        "Airtable, Baserow, Supabase.",
        [{"name": "GitHub", "url": "https://github.com/nocodb/nocodb"}])),

    # ============ Version control ============
    a(rec("git", "Git", [], "Software Freedom Conservancy", ["dev", "dev-ide"], "Version control",
        ["version control", "distributed VCS", "source code"],
        "open source", "GPL-2.0", "git/git",
        ["desktop", "server", "api"], ["local", "self-hosted"], "free",
        ["terminal", "local installation"], ["developer"],
        "Intermediate", "Low", "Developer-oriented", "None", "Low", "Very high",
        True, False, False, True, True, False, True, False, False, True, True,
        "free", "All developers; fundamental version control.",
        "Non-developers.",
        "Mercurial, Fossil, Darcs.",
        [{"name": "StackShare", "url": "https://stackshare.io/"}, {"name": "GitHub", "url": "https://github.com/git/git"}])),

    a(rec("github", "GitHub", [], "Microsoft", ["dev", "dev-devops"], "Dev platform",
        ["host git", "CI", "issues", "code review", "actions"],
        "proprietary", "Proprietary", None,
        ["web", "api"], ["cloud"], "freemium",
        ["account required"], ["developer", "technical team"],
        "Beginner+", "Instant", "Minimal", "None", "Low", "High",
        False, False, True, False, False, True, False, False, False, True, True,
        "freemium", "Developers/teams wanting hosted git + CI + collaboration.",
        "Users wanting fully self-hosted git hosting.",
        "GitLab, Gitea, Bitbucket.",
        [{"name": "GitHub", "url": "https://github.com/"}, {"name": "StackShare", "url": "https://stackshare.io/"}])),

    a(rec("gitea", "Gitea", [], "Gitea", ["dev", "dev-devops", "selfhost"], "Git hosting",
        ["self-hosted git", "lightweight", "forge"],
        "open source", "MIT", "go-gitea/gitea",
        ["web", "server", "api"], ["self-hosted"], "free",
        ["docker", "go"], ["developer", "technical team"],
        "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Teams wanting lightweight self-hosted git hosting.",
        "Teams wanting full CI/CD and marketplace.",
        "GitLab, Forgejo, GitHub.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/go-gitea/gitea"}])),

    # ============ Backup / storage sync ============
    a(rec("syncthing", "Syncthing", [], "Syncthing", ["prod-docs", "infra-storage", "selfhost"],
        "File sync", ["peer-to-peer file sync", "self-hosted"],
        "open source", "MPL-2.0", "syncthing/syncthing",
        ["desktop", "local"], ["self-hosted"], "free",
        ["local installation"], ["technical team", "privacy-focused"],
        "Intermediate", "Medium", "Moderate", "Manual", "High", "High",
        True, False, False, True, True, False, True, True, True, True, True,
        "free", "Users who want encrypted P2P file sync.",
        "Users wanting simple cloud sync.",
        "Nextcloud, Resilio, Dropbox.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/syncthing/syncthing"}])),

    # ============ Deployment / PaaS ============
    a(rec("docker", "Docker", [], "Docker", ["dev-devops", "dev"], "Containers",
        ["containerization", "deployment", "dev env"],
        "open source", "Apache-2.0", "moby/moby",
        ["server", "api"], ["local", "self-hosted", "cloud"], "freemium",
        ["docker", "terminal"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "Guided", "Moderate", "Very high",
        True, False, False, True, True, False, False, False, False, True, True,
        "freemium", "Developers who want to containerize apps for portability.",
        "Non-technical users.",
        "Podman, LXC, Kubernetes.",
        [{"name": "StackShare", "url": "https://stackshare.io/"}, {"name": "GitHub", "url": "https://github.com/moby/moby"}])),

    a(rec("vercel", "Vercel", [], "Vercel", ["dev-devops", "dev-frameworks", "dev"], "Hosting/PaaS",
        ["frontend hosting", "deploy previews", "serverless"],
        "proprietary", "Proprietary", None,
        ["web", "api"], ["cloud"], "freemium",
        ["account required", "git"], ["developer"],
        "Beginner+", "Instant", "Minimal", "None", "Low", "Moderate",
        False, False, True, False, False, True, False, False, False, True, True,
        "freemium", "Developers wanting fast, zero-ops frontend deployment.",
        "Users wanting full self-hosted control.",
        "Netlify, Railway, Coolify.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/business-software"},
         {"name": "Official", "url": "https://vercel.com"}])),

    a(rec("coolify", "Coolify", [], "Coolify", ["dev-devops", "dev", "selfhost"], "Self-hosted PaaS",
        ["self-hosted deployment", "one-click services", "paas"],
        "open source", "Apache-2.0", "coollabsio/coolify",
        ["web", "server"], ["self-hosted"], "free",
        ["docker", "server"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "One-click", "High", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Developers wanting to self-host PaaS-style deployments.",
        "Users wanting fully managed hosting.",
        "Vercel, Railway, Dokku.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/infrastructure-operations"},
         {"name": "GitHub", "url": "https://github.com/coollabsio/coolify"}])),

    # ============ Git / CLI / terminals ============
    a(rec("starship", "Starship", [], "Starship", ["dev-ide", "dev"], "Shell prompt",
        ["custom shell prompt", "cross-shell"],
        "open source", "ISC", "starship/starship",
        ["desktop", "local"], ["local"], "free",
        ["terminal", "install"], ["developer"],
        "Beginner+", "Low", "Minimal", "None", "Low", "Very high",
        True, False, False, True, False, False, True, False, False, False, False,
        "free", "Developers who want a polished, customized terminal prompt.",
        "Non-technical users.",
        "oh-my-zsh, powerlevel10k.",
        [{"name": "GitHub", "url": "https://github.com/starship/starship"}])),

    # ============ Email clients ============
    a(rec("thunderbird", "Thunderbird", [], "Mozilla", ["prod-email", "selfhost-mobile"], "Email client",
        ["email client", "open source", "calendar"],
        "open source", "MPL-2.0", "mozilla/thunderbird",
        ["desktop", "mobile"], ["local", "cloud"], "free",
        ["local installation"], ["beginner", "privacy-focused"],
        "Beginner", "Instant", "None", "None", "Low", "High",
        True, False, True, True, False, False, True, True, True, False, True,
        "free", "Users wanting a free, open-source email client.",
        "Users needing deep enterprise/Outlook integration.",
        "Outlook, ElectronMail, Mailspring.",
        [{"name": "GitHub", "url": "https://github.com/mozilla/thunderbird"}])),

    # ============ Education / LMS ============
    a(rec("moodle", "Moodle", [], "Moodle", ["business", "design", "selfhost"], "LMS",
        ["learning platform", "courses", "self-hosted LMS"],
        "open source", "GPL-3.0", "moodle/moodle",
        ["web", "local"], ["self-hosted"], "free",
        ["php", "mysql", "docker"], ["enterprise", "teacher", "technical team"],
        "Intermediate", "High", "Moderate", "Manual", "High", "Very high",
        True, False, False, True, True, True, False, True, True, True, True,
        "free", "Institutions wanting a self-hosted LMS.",
        "Solo course creators wanting a hosted product.",
        "Teachable, Canvas, Sakai.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/moodle/moodle"}])),

    # ============ Game engine ============
    a(rec("godot", "Godot", [], "Godot", ["design", "dev-mobile", "selfhost"], "Game engine",
        ["2D/3D/XR games", "open-source engine", "cross-platform"],
        "open source", "MIT", "godotengine/godot",
        ["desktop", "web", "mobile"], ["local"], "free",
        ["local installation", "build tools"], ["developer", "creator"],
        "Intermediate", "Medium", "Developer-oriented", "Manual", "Moderate", "Very high",
        True, False, False, True, False, True, True, True, True, False, True,
        "free", "Game developers who want a free, open-source engine.",
        "Users wanting a hosted game platform.",
        "Unity, Unreal, LÖVE.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/misc"},
         {"name": "GitHub", "url": "https://github.com/godotengine/godot"}])),

    # ============ Office suites ============
    a(rec("libreoffice", "LibreOffice", [], "The Document Foundation", ["prod-docs", "business", "selfhost"],
        "Office suite", ["docs", "spreadsheets", "presentations"],
        "open source", "MPL-2.0", "LibreOffice/core",
        ["desktop", "mobile"], ["local"], "free",
        ["local installation"], ["beginner", "privacy-focused", "team"],
        "Beginner", "Medium", "None", "None", "Low", "High",
        True, False, False, True, False, False, True, True, True, False, False,
        "free", "Users wanting a free, offline office suite.",
        "Users needing real-time cloud collaboration.",
        "Microsoft Office, OnlyOffice, Google Docs.",
        [{"name": "GitHub", "url": "https://github.com/LibreOffice/core"}])),

    a(rec("onlyoffice", "ONLYOFFICE", [], "ONLYOFFICE", ["prod-docs", "business", "selfhost"],
        "Office suite (self-hosted)", ["collaborative docs", "self-hosted office", "compatible"],
        "open source", "AGPL-3.0", "ONLYOFFICE/DocumentServer",
        ["web", "desktop", "mobile"], ["self-hosted", "cloud"], "freemium",
        ["docker"], ["team", "technical team", "enterprise"],
        "Beginner+", "Low", "Minimal", "One-click", "Moderate", "High",
        True, False, False, True, True, True, True, True, True, False, False,
        "freemium", "Teams wanting self-hosted collaborative office editing.",
        "Users wanting a fully free offline-only suite.",
        "LibreOffice, Collabora, Microsoft Office.",
        [{"name": "GitHub", "url": "https://github.com/ONLYOFFICE/DocumentServer"}])),

    # ============ Additional AI / agents / assistants ============
    a(rec("parlant", "Parlant", [], "Parlant", ["ai-agents", "ai-models", "selfhost"],
        "AI agent framework", ["customer-facing AI agents", "guidelines", "auditable"],
        "open source", "Apache-2.0", "emcie-co/parlant",
        ["web", "api", "local"], ["self-hosted", "cloud"], "free",
        ["node", "build tools"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "Manual", "Moderate", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Developers building governed, auditable customer-facing agents.",
        "Non-technical users.",
        "LangGraph, CrewAI, Voiceflow.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/ai-machine-learning"},
         {"name": "GitHub", "url": "https://github.com/emcie-co/parlant"}])),

    a(rec("flowise", "Flowise", [], "Flowise", ["ai-agents", "ai-models", "selfhost"],
        "Visual AI builder (LLM)", ["drag-drop LLM flows", "chatbots", "open source"],
        "open source", "Apache-2.0", "FlowiseAI/Flowise",
        ["web", "local"], ["cloud", "self-hosted"], "free",
        ["docker", "node"], ["developer", "technical team"],
        "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Developers wanting a visual LLM flow builder.",
        "Users wanting production-grade agent governance.",
        "Langflow, Dify, n8n.",
        [{"name": "GitHub", "url": "https://github.com/FlowiseAI/Flowise"}])),

    # ============ Finance / invoicing ============
    a(rec("invoiceplane", "InvoicePlane", [], "InvoicePlane", ["biz-finance", "business", "selfhost"],
        "Invoicing", ["invoicing", "payments", "self-hosted"],
        "open source", "MIT", "InvoicePlane/InvoicePlane",
        ["web", "local"], ["self-hosted"], "free",
        ["php", "mysql"], ["freelancer", "business", "technical team"],
        "Beginner+", "Medium", "Minimal", "Guided", "Moderate", "Moderate",
        True, False, False, True, True, True, False, False, False, False, True,
        "free", "Freelancers/small businesses wanting self-hosted invoicing.",
        "Enterprises needing robust accounting.",
        "FreshBooks, Crater, Akaunting.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/InvoicePlane/InvoicePlane"}])),

    a(rec("akaunting", "Akaunting", [], "Akaunting", ["biz-finance", "business", "selfhost"],
        "Accounting", ["accounting", "invoicing", "self-hosted"],
        "open source", "GPL-3.0", "akaunting/akaunting",
        ["web", "local"], ["self-hosted"], "free",
        ["php", "mysql"], ["business", "technical team"],
        "Beginner+", "Medium", "Minimal", "Guided", "Moderate", "Moderate",
        True, False, False, True, True, True, False, False, False, False, True,
        "free", "Small businesses wanting self-hosted accounting.",
        "Enterprises needing advanced tax/reporting.",
        "InvoicePlane, QuickBooks, Wave.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/akaunting/akaunting"}])),

    # ============ Web scraping SDKs ============
    a(rec("crawl4ai", "Crawl4AI", [], "Crawl4AI", ["data-scraping", "data", "ai-ml-infra"],
        "AI web crawler", ["LLM-ready crawling", "CSS/XPath extraction", "stealth browser"],
        "open source", "Apache-2.0", "unclecode/crawl4ai",
        ["api", "local"], ["local", "self-hosted"], "free",
        ["python", "pip"], ["developer"],
        "Advanced", "Medium", "Deep developer involvement", "Manual", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "free", "Developers building AI-oriented crawling pipelines.",
        "Beginners wanting a one-click hosted scraper.",
        "Firecrawl, Scrapy, Apify.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/data-analytics"},
         {"name": "GitHub", "url": "https://github.com/unclecode/crawl4ai"}])),

    # ============ Search engine / vector ============
    a(rec("elasticsearch", "Elasticsearch", [], "Elastic", ["data", "infra-storage", "infra-monitoring"],
        "Search engine", ["full-text search", "analytics", "log analysis"],
        "open source", "Elastic License / AGPL", "elastic/elasticsearch",
        ["server", "api"], ["self-hosted", "cloud"], "free",
        ["java", "docker", "memory"], ["technical team", "developer"],
        "Advanced", "High", "Developer-oriented", "Manual", "High", "Very high",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Teams needing powerful full-text search/analytics.",
        "Small apps wanting a simple DB search.",
        "Meilisearch, Typesense, Algolia.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/infrastructure-operations"},
         {"name": "GitHub", "url": "https://github.com/elastic/elasticsearch"}])),

    a(rec("meilisearch", "Meilisearch", [], "Meilisearch", ["data", "infra-storage", "selfhost"],
        "Search engine", ["fast search", "typ-tolerance", "self-hosted"],
        "open source", "MIT", "meilisearch/meilisearch",
        ["server", "api"], ["self-hosted", "cloud"], "free",
        ["docker"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "One-click", "Moderate", "High",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Developers wanting a fast, simple self-hosted search engine.",
        "Teams needing advanced analytics/aggregations.",
        "Elasticsearch, Typesense, Algolia.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/meilisearch/meilisearch"}])),

    # ============ Screenshot / capture ============
    a(rec("cap", "Cap", [], "Cap", ["design-video", "design", "selfhost"], "Screen recorder",
        ["screen recording", "edit + share", "open source"],
        "open source", "AGPL-3.0", "CapSoftware/Cap",
        ["desktop", "web"], ["cloud", "local"], "freemium",
        ["local installation"], ["creator", "developer"],
        "Beginner+", "Low", "Minimal", "None", "Low", "Moderate",
        True, False, False, True, False, True, True, False, False, False, False,
        "freemium", "Creators wanting a simple open-source screen recorder.",
        "Users needing pro-grade video editing.",
        "OBS, Loom, Screen Studio.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/productivity-utilities"},
         {"name": "GitHub", "url": "https://github.com/CapSoftware/Cap"}])),

    a(rec("obs", "OBS Studio", ["obs"], "OBS Project", ["design-video", "design"], "Streaming/recording",
        ["live streaming", "screen capture", "broadcast"],
        "open source", "GPL-2.0", "obsproject/obs-studio",
        ["desktop"], ["local"], "free",
        ["local installation"], ["creator", "streamer"],
        "Intermediate", "Medium", "Minimal", "None", "Moderate", "Very high",
        True, False, False, True, False, False, True, False, False, False, False,
        "free", "Streamers/creators who want pro-level capture and streaming.",
        "Users wanting a quick, simple recorder.",
        "Cap, Loom, Streamlabs.",
        [{"name": "GitHub", "url": "https://github.com/obsproject/obs-studio"}])),

    # ============ Remote desktop ============
    a(rec("rustdesk", "RustDesk", [], "RustDesk", ["dev", "infra-security", "selfhost"],
        "Remote desktop", ["remote desktop", "self-hosted", "cross-platform"],
        "open source", "AGPL-3.0", "rustdesk/rustdesk",
        ["desktop", "mobile"], ["self-hosted", "cloud"], "free",
        ["local installation"], ["developer", "technical team"],
        "Intermediate", "Low", "Minimal", "One-click", "Moderate", "Moderate",
        True, False, False, True, False, False, True, True, True, False, False,
        "free", "Users wanting a self-hosted remote desktop tool.",
        "Users wanting a polished managed remote solution.",
        "TeamViewer, AnyDesk, Chrome Remote Desktop.",
        [{"name": "GitHub", "url": "https://github.com/rustdesk/rustdesk"}])),

    # ============ Integrations / API gateways ============
    a(rec("n8n_extra", "n8n", [], "n8n", ["prod-automation", "dev"], "Integration", [],
        "open source", "Sustainable Use License", "n8n-io/n8n", [], [], "freemium",
        [], [], "Intermediate", "Medium", "Moderate", "One-click", "Moderate", "Very high",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "", "", "",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/developer-tools"}], "placeholder-skip")),
    # remove placeholder
    tools.pop()

    # ============ Additional: Online design / whiteboard ============
    a(rec("excalidraw", "Excalidraw", [], "Excalidraw", ["design-uiux", "prod-docs", "selfhost"],
        "Whiteboard", ["hand-drawn diagrams", "collaborative whiteboard"],
        "open source", "MIT", "excalidraw/excalidraw",
        ["web", "local"], ["cloud", "self-hosted"], "free",
        ["account optional"], ["designer", "developer", "team"],
        "Beginner", "Very low", "None", "None", "None", "High",
        True, False, False, True, True, True, False, False, False, False, False,
        "free", "Teams wanting a simple collaborative whiteboard.",
        "Users needing structured diagramming/flowcharts.",
        "Miro, FigJam, Tldraw.",
        [{"name": "GitHub", "url": "https://github.com/excalidraw/excalidraw"}])),

    # ============ Integration / API platform ============
    a(rec("zapier", "Zapier", [], "Zapier", ["prod-automation", "business"], "Automation (SaaS)",
        ["no-code automation", "app integrations"],
        "proprietary", "Proprietary", None,
        ["web"], ["cloud"], "freemium",
        ["account required"], ["beginner", "entrepreneur", "team"],
        "Beginner", "Instant", "None", "None", "None", "Moderate",
        False, False, True, False, False, True, False, False, False, False, True,
        "freemium", "Non-technical users wanting hosted automation.",
        "Developers wanting self-hosted/code-first automation.",
        "Make, n8n, Activepieces.",
        [{"name": "Capterra", "url": "https://www.capterra.com/"}, {"name": "Official", "url": "https://zapier.com"}])),

    # ============ Hosting for selfhost: additional dev tools ============
    a(rec("traefik", "Traefik", [], "Traefik Labs", ["dev-devops", "infra", "selfhost"], "Reverse proxy",
        ["reverse proxy", "ingress", "auto TLS"],
        "open source", "MIT", "traefik/traefik",
        ["server", "api"], ["self-hosted"], "free",
        ["docker"], ["developer", "technical team"],
        "Advanced", "High", "Developer-oriented", "Manual", "High", "Very high",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Developers who need a modern reverse proxy/ingress.",
        "Users wanting a managed load balancer.",
        "Nginx, Caddy, HAProxy.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/traefik/traefik"}])),

    a(rec("caddy", "Caddy", [], "Caddy", ["dev-devops", "infra", "selfhost"], "Web server",
        ["web server", "auto HTTPS", "reverse proxy"],
        "open source", "Apache-2.0", "caddyserver/caddy",
        ["server", "api"], ["self-hosted"], "free",
        ["docker", "go"], ["developer", "technical team"],
        "Intermediate", "Low", "Moderate", "One-click", "Moderate", "High",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Developers wanting simple auto-TLS serving.",
        "Users needing deep enterprise load-balancing.",
        "Nginx, Traefik, Apache.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"},
         {"name": "GitHub", "url": "https://github.com/caddyserver/caddy"}])),

    # ============ Awesome: automation / LLM agent ============
    a(rec("langchain", "LangChain", [], "LangChain", ["ai-models", "ai-agents", "ai-ml-infra"],
        "LLM framework", ["LLM apps", "agents", "RAG pipelines"],
        "open source", "MIT", "langchain-ai/langchain",
        ["api", "local"], ["local", "cloud"], "free",
        ["python", "pip", "build tools"], ["developer", "technical team"],
        "Advanced", "Medium", "Deep developer involvement", "Manual", "Moderate", "Very high",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Developers building complex LLM applications/agents.",
        "Beginners wanting visual/no-code LLM tooling.",
        "LangGraph, LlamaIndex, CrewAI.",
        [{"name": "GitHub", "url": "https://github.com/langchain-ai/langchain"}])),

    a(rec("autogen", "AutoGen", [], "Microsoft", ["ai-agents", "ai-models", "ai-ml-infra"],
        "Multi-agent framework", ["multi-agent", "agent orchestration", "conversational agents"],
        "open source", "MIT", "microsoft/autogen",
        ["api", "local"], ["local", "cloud"], "free",
        ["python", "pip"], ["developer", "researcher"],
        "Advanced", "Medium", "Deep developer involvement", "Manual", "Moderate", "Very high",
        True, False, False, True, True, False, False, False, False, True, True,
        "free", "Researchers/developers building multi-agent LLM systems.",
        "Beginners wanting a hosted agent product.",
        "LangGraph, CrewAI, OpenAI Agents.",
        [{"name": "GitHub", "url": "https://github.com/microsoft/autogen"}])),

    # ============ More: marketing / CMS ============
    a(rec("strapi", "Strapi", [], "Strapi", ["prod-docs", "business", "selfhost"], "Headless CMS",
        ["headless CMS", "REST/GraphQL", "content API"],
        "open source", "MIT", "strapi/strapi",
        ["web", "api", "local"], ["self-hosted", "cloud"], "freemium",
        ["docker", "node"], ["developer", "technical team"],
        "Intermediate", "Medium", "Developer-oriented", "One-click", "Moderate", "High",
        True, False, False, True, True, True, False, False, False, True, True,
        "freemium", "Developers who want a flexible headless CMS.",
        "Non-developers wanting a full website builder.",
        "Payload, Directus, Sanity.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/content-publishing"},
         {"name": "GitHub", "url": "https://github.com/strapi/strapi"}])),

    a(rec("ghost", "Ghost", [], "Ghost", ["prod-docs", "business", "selfhost"], "Publishing platform",
        ["blogs", "newsletters", "memberships"],
        "open source", "MIT", "TryGhost/Ghost",
        ["web", "local"], ["cloud", "self-hosted"], "freemium",
        ["docker", "node"], ["creator", "entrepreneur"],
        "Beginner+", "Low", "Minimal", "One-click", "Low", "High",
        True, False, True, False, True, True, False, False, False, True, True,
        "freemium", "Creators/publishers wanting a modern publishing platform.",
        "Users wanting a full CMS with plugins.",
        "WordPress, Payload, Substack.",
        [{"name": "OpenAlternative", "url": "https://openalternative.co/categories/content-publishing"},
         {"name": "GitHub", "url": "https://github.com/TryGhost/Ghost"}])),

    # ============ Calendar / scheduling ============
    a(rec("caldav", "CalDAV", [], "Calendaring community", ["prod-email", "business", "selfhost"], "Calendaring",
        ["shared calendars", "self-hosted"],
        "open source", "various", None,
        ["web", "api"], ["self-hosted"], "free",
        ["server"], ["technical team"],
        "Intermediate", "High", "Developer-oriented", "Manual", "Moderate", "Moderate",
        True, False, False, True, True, True, True, True, True, True, True,
        "free", "Teams wanting standardized self-hosted calendaring.",
        "Users wanting a hosted calendar app.",
        "Google Calendar, Nextcloud Calendar, Radicale.",
        [{"name": "Awesome-Selfhosted", "url": "https://awesome-selfhosted.net/"}])),

    return tools


if __name__ == "__main__":
    t = build_seed()
    print("seed tools:", len(t))
    # dedupe by tool_id
    seen = {}
    for x in t:
        seen.setdefault(x["tool_id"], x)
    print("unique tool_ids:", len(seen))
